### ISSUE TITLE
微软的PowerToys中的PowerRename无法使用

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#323]
[PowerToys项目地址](https://github.com/microsoft/PowerToys/tree/v0.43.0)
在RX文件管理器中按住Shift的同时,右键调出PowerRename,只会出现
![屏幕截图 2021-08-13 170329](https://user-images.githubusercontent.com/62456287/129333664-1e470e52-d8be-4600-b358-ebae0d98c347.png)
在Windows自带的资源管理器中出现这个的同时,可以出现
![屏幕截图 2021-08-13 171029](https://user-images.githubusercontent.com/62456287/129334074-efc3d689-65f9-4a94-a6c7-3dbe11d56c7f.png)

**Comment by zhuxb711** [comment]
看了PowerToy的代码，应该是 [这里](https://github.com/microsoft/PowerToys/blob/bf6dcf40ef597bf75872a173005430f3723ae55d/src/modules/powerrename/ui/PowerRenameUI.cpp#L1561) 卡住了

原因不太清楚，似乎是PowerToy不能正确识别RX指定要处理哪个文件。然而菜单项触发机制不需要手动指定哪个文件，因为获取菜单项的过程已经自动指定了是哪些文件，你可以发现其他软件都可以正常识别RX的启动指令，PowerToy不行只能说明是PowerToy的设计有问题。

当然如果能够指出是RX哪一部分存在问题从而导致了该问题的话，将会进行更正，但目前没有发现任何问题

@silentmoooon 有木有兴趣看看？Files就可以正常激活 (摔！)，把RX所有与菜单项启动的内容调整成和Files完全一致，Files行RX不行，，淦

**Comment by silentmoooon** [comment]
照着files的试了一下, FetchContextMenuItems时把ContextObject保存起来,然后Invoke时复用它就可以了.
另外,最新版貌似也把那个调试疯狂报错的BUG给解决了

**Comment by silentmoooon** [comment]
但是就第一下可以,第二下又不行了.

**Comment by zhuxb711** [comment]
> 照着files的试了一下, FetchContextMenuItems时把ContextObject保存起来,然后Invoke时复用它就可以了.
> 另外,最新版貌似也把那个调试疯狂报错的BUG给解决了

保存起来的问题是，Invoke的时候好像激活不到那些菜单项了，所以才Invoke的时候临时fetch一遍

**Comment by silentmoooon** [comment]
好像是有这个问题..  就第一次打开是正常的 第2次就不行.  
但files咋就可以了.

**Comment by zhuxb711** [comment]
> 好像是有这个问题.. 就第一次打开是正常的 第2次就不行.
> 但files咋就可以了.

Files老防Copy代码了。它的可以，你Copy过来--不行

**Comment by zhuxb711** [comment]
总之我是不知道怎么搞了，你要是研究出来告诉我，谢谢~

**Comment by silentmoooon** [comment]
emmm  我也没研究出个所以然

**Comment by silentmoooon** [comment]
把invoke的Helper.ExecuteOnSTAThreadAsync 去掉就好了.

**Comment by zhuxb711** [comment]
> 把invoke的Helper.ExecuteOnSTAThreadAsync 去掉就好了.

所以Fetch需要STA，Invoke不需要STA？

**Comment by silentmoooon** [comment]
也许吧






-------- 原始邮件 --------
发件人： Ruofan ***@***.***>
日期： 2021年8月28日周六 15:04
收件人： zhuxb711/RX-Explorer ***@***.***>
抄送： silentmoon ***@***.***>, Mention ***@***.***>
主 题： Re: [zhuxb711/RX-Explorer] 微软的PowerToys中的PowerRename无法使用 (#323)

把invoke的Helper.ExecuteOnSTAThreadAsync 去掉就好了.

所以Fetch需要STA，Invoke不需要STA？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzhuxb711%2FRX-Explorer%2Fissues%2F323%23issuecomment-907584458&data=04%7C01%7C%7C101355efc26046721a0908d969f2057c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637657310467901993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jkaqZ6ceoZTBc%2FfmmbHnnMP4P%2F0E2WO6C3KlqJorKUE%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACGIVEWT57LIOA3K2RR5NN3T7CC6HANCNFSM5CDGFWKA&data=04%7C01%7C%7C101355efc26046721a0908d969f2057c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637657310467901993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tl0X3GLbgLgT5W7xRjqnlzri1tn6MQZI%2FQMB2AM4w0Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C101355efc26046721a0908d969f2057c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637657310467911949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=urKU5DU8fijOSYOtzGv55NyTMr1AC%2B%2FEo4X1IQIVfk4%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C101355efc26046721a0908d969f2057c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637657310467911949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YP02rlzNfzOF7Bmx6YqfHZkWc7FB8enhyzIPS%2B%2FjPp4%3D&reserved=0>.

**Comment by zhuxb711** [comment]
> 把invoke的Helper.ExecuteOnSTAThreadAsync 去掉就好了.

去掉会导致Invoke时候Fetch的那一遍不在STA中运行，所以会导致有些内容检索不到的呀

**Comment by silentmoooon** [comment]
额...
要不再把前一次fetch的缓存起来?

**Comment by zhuxb711** [comment]
> 额...
> 要不再把前一次fetch的缓存起来?

关键是前一次Fetch出来的IContextMenu接口不通用呀，后面Invoke时再用就不行了的说

**Comment by silentmoooon** [comment]
这个ContextObject是通用的吧

**Comment by zhuxb711** [comment]
现在的问题不就是，把ContextObject提升为全局变量后，无法再次用它去Invoke吗？

**Comment by silentmoooon** [comment]
emm... 好像是这么回事, 过了几天又有点忘记了

**Comment by silentmoooon** [comment]
要不改成用[STAThread],  貌似这种是可以的

**Comment by zhuxb711** [comment]
你提交一个PR看看吗？

**Comment by zhuxb711** [comment]
7.0.2已发布并包含此问题的修复补丁
