### ISSUE TITLE
request

### ISSUE THREAD

**Issue by HarkTu** [zhuxb711/RX-Explorer#391]
minimize  to tray area on 'x' close button.

**Comment by zhuxb711** [comment]
Sorry but that is no possible for UWP Application [See here](https://docs.microsoft.com/answers/questions/764727/is-it-possible-to-close-the-uwp-app-when-clicked-o.html)

**Comment by HarkTu** [comment]
if I did not understand wrong it says it is possible with an extension
https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/UWP Systray

**Comment by zhuxb711** [comment]
Actually RX-Explorer is using the technology like the blog mentioned. System tray is possible but that will not make RX-Explorer launch faster.

Because that blog create a separate process for the tray. What it does is help you create a new instance of RX once you press it. There is no difference between close RX and launch it again.

**Comment by HarkTu** [comment]
ok got it. I thought its possible since 'one commander' does it. they probably use different technology

**Comment by zhuxb711** [comment]
> ok got it. I thought its possible since 'one commander' does it. they probably use different technology

One commander is not an UWP Application. UWP do not have similar technology like Win32 applications. 

Microsoft: For your safety and you don't need that!

**Comment by zhuxb711** [comment]
> ok got it. I thought its possible since 'one commander' does it. they probably use different technology

One commander is not an UWP Application. UWP do not have similar technology like Win32 applications. 

Microsoft: For your safety and you don't need that!
