### ISSUE TITLE
[Bug] can't open file in another application when drag and drop default is Move

### ISSUE THREAD

**Issue by alient12** [zhuxb711/RX-Explorer#426]
Hi, thanks for your great works. I've found two bugs during drag and drop when it was Move by default.

**1.  can't drag subtitle to PotPlayer:**

![Screenshot (3)](https://user-images.githubusercontent.com/73688480/189478111-93b70714-c838-40a9-823e-9e5d458b5321.png)

even I can't put screenshot on the browser

![Screenshot (4)](https://user-images.githubusercontent.com/73688480/189478152-b36cdeba-ab2f-43c1-83f4-f1b10331a847.png)

**2. I can't change the drag and drop mode via holding Shift or Ctrl buttons. It sometimes works but not most of the time.**

Edition: Windows 11 Home
Version: 21H2
OS Build: 22000.856

RX-Explorer:
Version: 7.9.1.0

**Comment by zhuxb711** [comment]
Hi, a drag and drop operation depends on both drag-out and drag-in application. You ask RX-Explorer to send "Move" request to the other applications and it would be accepted by these application if they allowed to do that. 

In this case, not all the applications that accept "Move" request. That's why you could not drop the files on them. You should not blame RX-Explorer. 

This is not a bug. Every application could determine what operations is accepted and reject the others.

**Comment by alient12** [comment]
Hi, thanks for your response but I think the second one is bug. Because in Windows Explorer I can change drag and drop mode by holding Shift or Ctrl. But it sometimes works.

**Comment by zhuxb711** [comment]
Switching from Move & Copy by pressing Ctrl is implemented by target applications. It's not controlled from RX-Explorer.

**Comment by alient12** [comment]
The target application is RX-Explorer and it's not working!

![Screenshot (5)](https://user-images.githubusercontent.com/73688480/189611631-d7b8c264-6c9e-4852-9be0-e772e8eb5fe5.png)

**Comment by zhuxb711** [comment]
Sorry for miss understanding. If you want to change the mode of dragging on RX-Explorer. You should press and hold on the ctrl key and move your mouse slightly.

**Comment by alient12** [comment]
Thank you, now I see it works. But there is another problem, It won't allow me to copy a file to another folder. The folders are ordinary folders on my Desktop.
![Screenshot (6)](https://user-images.githubusercontent.com/73688480/189614190-501e2cdd-42bf-4e4c-a776-ec712fdabb18.png)

**Comment by zhuxb711** [comment]
I think that should be a bug. The application which you dragged into will only be able to execute the actions requested from the original application.

So that's why you could not change the actions when pressing Ctrl key. In the next version of RX-Explorer, it will respect the request from other applications and user could not switch the actions to those not allowed by original application (If original application requests Move then user could not change it to Copy by pressing Ctrl key)

I will add a new option to Default Drag Behavior: Not specified. To allow user switching Copy/Move actions by pressing ctrl key. If you select 'Copy' or 'Move' as default behavior then you will no longer allowed to switch the actions.
